In [33]:
import numpy as np

k = 4
n = 200
data = np.random.randn(n, 2)

centroids = data[np.random.choice(np.arange(n), size=(k,))]
print(centroids)

for l in range(10):
  indexes = np.zeros(data.shape[0])
  for centroid in centroids:  # <--この行いらない
    for i, x in enumerate(data):
      if i == 0:
        print(np.sum((x - centroids) ** 2, axis=1))
      indexes[i] = np.argmin(np.sum((x - centroids) ** 2, axis=1))
  
  for i in range(k):
    centroids[i] = data[indexes == i].mean(axis=0)

print(centroids)

[[ 0.62465857  0.4997301 ]
 [-0.06100073  0.21505601]
 [ 0.9433261   1.37967839]
 [ 0.54762436 -0.23360219]]
[0.63213906 0.0226734  2.69634668 0.43670089]
[0.63213906 0.0226734  2.69634668 0.43670089]
[0.63213906 0.0226734  2.69634668 0.43670089]
[0.63213906 0.0226734  2.69634668 0.43670089]
[1.16415814 0.77055231 2.72045008 1.46603693]
[1.16415814 0.77055231 2.72045008 1.46603693]
[1.16415814 0.77055231 2.72045008 1.46603693]
[1.16415814 0.77055231 2.72045008 1.46603693]
[1.0417201  1.10192117 2.64857184 1.38660906]
[1.0417201  1.10192117 2.64857184 1.38660906]
[1.0417201  1.10192117 2.64857184 1.38660906]
[1.0417201  1.10192117 2.64857184 1.38660906]
[0.80600406 1.40778208 2.15295122 1.48292305]
[0.80600406 1.40778208 2.15295122 1.48292305]
[0.80600406 1.40778208 2.15295122 1.48292305]
[0.80600406 1.40778208 2.15295122 1.48292305]
[0.65058014 1.731847   1.89965298 1.50460219]
[0.65058014 1.731847   1.89965298 1.50460219]
[0.65058014 1.731847   1.89965298 1.50460219]
[0.65058014 1.731

[[-1.02723074  0.41068412]
 [-0.38449033 -1.26861788]
 [ 0.85167276 -0.72379743]
 [ 0.65299283  0.77243459]]

In [23]:
data = [[2, 3], 
        [2, 3]]

print(data)
print(np.sum(data, axis=0))

[[2, 3], [2, 3]]
[4 6]
