In [ ]:
import numpy as np

k = 3
n_data = 50
X = np.random.randint(0, 100, n_data)
print(X)

[25  4 84 49 87 53 59 92 77 75 39 93  7 14 82 88 30 27 97 91  5 33  3 13
 40 76 10 67 72 69 67 71 96 25 47 38 15 36 16  0 59 87 91 36 67 48 54 53
 10 10]


In [ ]:
idx = np.random.permutation(n_data)[:k]
c = X[idx]
print(idx)
print(c)

[38 13 24]
[16 14 40]


In [ ]:
idx = np.random.choice(n_data, k)
c = X[idx]
print(idx)
print(c)

[ 0 19 41]
[25 91 87]


In [ ]:
idx = np.random.rand(n_data, k)
print(idx)
c = X[idx]
print(c)

[[0.14823581 0.59971726 0.05679954]
 [0.0519769  0.6339221  0.77304732]
 [0.99396584 0.14826856 0.9778935 ]
 [0.69889303 0.51883891 0.82156656]
 [0.36858556 0.92810115 0.09727682]
 [0.00216474 0.81518639 0.41816465]
 [0.93564255 0.91120579 0.13342222]
 [0.76849135 0.31432386 0.77675404]
 [0.22433383 0.66215424 0.61241564]
 [0.82925321 0.03727436 0.8195754 ]
 [0.61353944 0.56939576 0.6078002 ]
 [0.85132072 0.54935376 0.66445533]
 [0.21745762 0.79911611 0.79252171]
 [0.89398322 0.52193154 0.93035572]
 [0.77939574 0.3815353  0.80922294]
 [0.16139387 0.91324736 0.56194585]
 [0.77114072 0.72208843 0.04358538]
 [0.61229045 0.67595571 0.93295128]
 [0.75811368 0.48322826 0.66893814]
 [0.09887639 0.20615671 0.49472048]
 [0.90595353 0.72118433 0.84637006]
 [0.7111848  0.00558079 0.04294947]
 [0.93580351 0.47411178 0.2544261 ]
 [0.86611408 0.40072678 0.58714808]
 [0.82832647 0.4667812  0.09735889]
 [0.04120106 0.65615973 0.85748825]
 [0.66099982 0.76656651 0.90419045]
 [0.71120797 0.38847652 0.47

IndexError: ignored

In [ ]:
idx = np.random.randint(0, n_data, k)
print(idx)
c = X[idx]
print(c)

[38 49 29]
[16 10 69]


In [ ]:
import numpy as np

def init_centroid(X, n_data, k):
  idx = np.random.permutation(n_data)[:k]
  centroids = X[idx]
  return centroids

def compute_distance(X, k, n_data, centroids):
  distances = np.zeros((n_data, k))
  for idx_centroids in range(k):
    dist = np.sqrt(np.sum((X - centroids[idx_centroids]) ** 2, axis=1))
    distances[:, idx_centroids] = dist
  return distances

def k_means(k, X, max_iter=300):
  n_data, n_features = X.shape
  centroids = init_centroid(X, n_data, k)
  new_cluster = np.zeros(n_data)
  cluster = np.zeros(n_data)

  # for epoch in range(max_iter):
  distances = compute_distance(X, k, n_data, centroids)
  print(distances)
  new_cluster = np.argmin(distances, axis=1)

  for idx_centroids in range(k):
    centroids[idx_centroids] = X[new_cluster == idx_centroids].mean(axis=0)
    # print(new_cluster)
    # print(idx_centroids)
  
  # if (new_cluster == cluster).all():
  #   break

  cluster = new_cluster
  
  return cluster

k = 3
n_data = 20
X = np.random.randint(0, 100, (n_data, 2))
print(X)

cluster = k_means(k, X)
print(cluster)

[[77 98]
 [77 26]
 [92 23]
 [94 65]
 [75 61]
 [45 35]
 [51 33]
 [10 44]
 [66 62]
 [29  6]
 [ 2 30]
 [13 81]
 [58 87]
 [50 99]
 [84  1]
 [21  6]
 [53 26]
 [43  1]
 [57 19]
 [38 48]]
[[37.05401463 21.9544984  75.89466384]
 [35.05709629 63.89053138 24.        ]
 [41.62931659 72.47068373 39.11521443]
 [19.41648784 42.19004622 56.5862174 ]
 [ 0.         31.06444913 41.34005322]
 [39.69886648 53.60037313 12.04159458]
 [36.87817783 54.45181356  7.28010989]
 [67.18630813 64.44377394 46.61544808]
 [ 9.05538514 26.2488095  38.27531842]
 [71.70076708 86.03487665 31.2409987 ]
 [79.30952024 79.906195   51.15662225]
 [65.1459899  45.39823785 68.00735254]
 [31.06444913  0.         61.20457499]
 [45.48626166 14.4222051  73.06161783]
 [60.67124525 89.84430978 39.8246155 ]
 [77.07788269 89.05054744 37.73592453]
 [41.34005322 61.20457499  0.        ]
 [68.         87.29833904 26.92582404]
 [45.69463864 68.00735254  8.06225775]
 [39.2173431  43.829214   26.62705391]]
[1 2 2 0 0 2 2 2 0 2 2 1 1 1 2 2 2 2 2

In [ ]:
dist = np.random.rand(20, 3)
print(dist)

[[0.85993351 0.03717389 0.10767998]
 [0.87669288 0.79095668 0.07569409]
 [0.89787112 0.18020109 0.18975589]
 [0.78200443 0.13737537 0.95408046]
 [0.77692001 0.20081784 0.69187706]
 [0.24142565 0.2881848  0.97719331]
 [0.60182822 0.48908032 0.52184849]
 [0.90294984 0.19046537 0.72632762]
 [0.67669709 0.48696521 0.12546179]
 [0.76209262 0.94597795 0.01251007]
 [0.49978314 0.80311591 0.21070877]
 [0.96290762 0.1931263  0.27182335]
 [0.6521679  0.1646056  0.86270319]
 [0.23769897 0.90263007 0.84320111]
 [0.00278094 0.2842137  0.22479894]
 [0.88730171 0.66759344 0.80662749]
 [0.19176026 0.46107173 0.18350501]
 [0.47123686 0.20329077 0.72094695]
 [0.81177493 0.88316688 0.9317234 ]
 [0.11988138 0.63600178 0.36698982]]


In [ ]:
new_cluster = np.amin(dist, axis=1)
print(new_cluster)

[0.03717389 0.07569409 0.18020109 0.13737537 0.20081784 0.24142565
 0.48908032 0.19046537 0.12546179 0.01251007 0.21070877 0.1931263
 0.1646056  0.23769897 0.00278094 0.66759344 0.18350501 0.20329077
 0.81177493 0.11988138]


In [ ]:
new_cluster = np.argmin(dist, axis=1)
print(new_cluster)

[1 2 1 1 1 0 1 1 2 2 2 1 1 0 0 1 2 1 0 0]


In [ ]:
new_cluster = dist.min(axis=1)
print(new_cluster)

[0.03717389 0.07569409 0.18020109 0.13737537 0.20081784 0.24142565
 0.48908032 0.19046537 0.12546179 0.01251007 0.21070877 0.1931263
 0.1646056  0.23769897 0.00278094 0.66759344 0.18350501 0.20329077
 0.81177493 0.11988138]


In [ ]:
new_cluster = np.minimum(dist, 0, axis=1)
print(new_cluster)

TypeError: ignored

In [ ]:
np.minimum([0, 1, 2], [2, 3, 4])

array([0, 1, 2])

In [9]:
import numpy as np

def compute_distance(X, k, n_data, centroids):
  distances = np.zeros((n_data, k))
  for idx_centroids in range(k):
    dist = np.sqrt(np.sum((X - centroids[idx_centroids]) ** 2, axis=1))
    distances[:, idx_centroids] = dist
  return distances

def k_means(k, X, max_iter=300):
  n_data, n_features = X.shape
  centroids = init_centroid(X, n_data, k)
  new_cluster = np.zeros(n_data)
  cluster = np.zeros(n_data)

  for epoch in range(max_iter):
    distances = compute_distance(X, k, n_data, centroids)
    # print(distances)
    new_cluster = np.argmin(distances, axis=1)

    for idx_centroids in range(k):
      centroids[idx_centroids] = X[new_cluster == idx_centroids].mean(axis=0)
    # print(new_cluster)
    # print(idx_centroids)
  
    if (new_cluster == cluster).all():
      break

  cluster = new_cluster
  
  return cluster

def init_centroid(X, n_data, k):
  idx = np.random.choice(n_data, 1)
  centroids = X[idx]
  for i in range(k-1):
    distances = compute_distance(X, len(centroids), n_data, centroids)
    print(distances)
    closest_dist_sq = np.min(distances ** 2, axis=1)
    print(closest_dist_sq)
    weights = closest_dist_sq.sum()
    print(weights)
    rate = np.random.random_sample()
    print(rate)
    rand_vals = rate * weights
    print(rand_vals)
    candidate_ids = np.searchsorted(np.cumsum(closest_dist_sq), rand_vals)
    centroids = np.vstack([centroids, X[candidate_ids]])
  return centroids

k = 3
n_data = 10
X = np.random.randint(0, 100, (n_data, 2))
# print(X)

cluster = k_means(k, X)
print(cluster)

[[17.08800749]
 [40.11234224]
 [ 3.60555128]
 [94.04786016]
 [14.31782106]
 [24.0208243 ]
 [ 0.        ]
 [34.        ]
 [29.54657341]
 [84.30895563]]
[ 292. 1609.   13. 8845.  205.  577.    0. 1156.  873. 7108.]
20678.0
0.25227246161765626
5216.489961329896
[[ 17.08800749 108.5771615 ]
 [ 40.11234224  67.95586803]
 [  3.60555128  94.20191081]
 [ 94.04786016   0.        ]
 [ 14.31782106  80.        ]
 [ 24.0208243   74.95331881]
 [  0.          94.04786016]
 [ 34.          79.55501241]
 [ 29.54657341  82.80096618]
 [ 84.30895563  86.00581376]]
[ 292. 1609.   13.    0.  205.  577.    0. 1156.  873. 7108.]
11833.0
0.7154877192299552
8466.36618164806
[0 0 0 1 0 0 0 0 0 2]


In [5]:
import numpy as np

hoge = [1, 2, 40, 55]
ret = np.searchsorted(hoge, 41)
print(ret)
print(hoge[ret])

3
55


In [8]:
import numpy as np

def pca(X, n_components=2):
  X = X - X.mean(axis=0)
  # 共分散行列の作成
  cov = np.cov(X, rowvar=False)
  print(cov)
  # 固有値や主成分方向を計算
  l, v = np.linalg.eig(cov)
  print(l)
  print(v)
  # 固有値の大きい順に並び替え
  l_index = np.argsort(l)[::-1]
  v_ = v[:, l_index]
  # n_components分、主成分方向を取得
  components = v_[:, :n_components]
  T = np.dot(X, components)
  return T

from sklearn.datasets import load_iris
iris = load_iris()
dst = pca(iris.data)
print(dst[:10])
print(iris.data.shape)
print(dst.shape)

[[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]
[4.22824171 0.24267075 0.0782095  0.02383509]
[[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]
[[-2.68412563 -0.31939725]
 [-2.71414169  0.17700123]
 [-2.88899057  0.14494943]
 [-2.74534286  0.31829898]
 [-2.72871654 -0.32675451]
 [-2.28085963 -0.74133045]
 [-2.82053775  0.08946138]
 [-2.62614497 -0.16338496]
 [-2.88638273  0.57831175]
 [-2.6727558   0.11377425]]
(150, 4)
(150, 2)
