In [6]:
import numpy as np

n = 100
k = 4
data = np.random.randn(n, 2)
prob = np.repeat(1/n, n)
print(prob)
centroids = np.zeros((k, 2))
distances = np.zeros((n, k))

for i in range(k):
  centroids[i] = data[np.random.choice(np.arange(n), p=prob, size=(1))]
  distances[:, i] = np.sum((data - centroids[i])**2, axis=1)
  prob = np.sum(distances, axis=1) / np.sum(distances)
  print(distances)
  print(prob)
  print(len(prob))

[0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01]
[[ 1.54546178  0.          0.          0.        ]
 [ 2.62816516  0.          0.          0.        ]
 [ 5.6109746   0.          0.          0.        ]
 [ 3.09281039  0.          0.          0.        ]
 [ 5.54850376  0.          0.          0.        ]
 [ 3.6581102   0.          0.          0.        ]
 [ 3.87826092  0.          0.          0.        ]
 [ 1.18458808  0.          0.          0.        ]
 [ 7.75949802  0.          0.          0.        ]
 [ 0.06315645  0.          0.   

In [ ]:
import numpy as np

x = [1, 2]
centroid = [5,1]
distance = np.sum((x - centroid)**2, axis=1)
print(distance)

TypeError: ignored

In [ ]:
data = np.random.randn(100, 2)
print(data)

[[-1.46011327 -1.14851968]
 [ 1.13487744 -0.22156216]
 [-0.18570461  0.90511918]
 [ 0.26700826 -1.26180781]
 [ 1.30743005  0.06684283]
 [ 1.96799633  0.962257  ]
 [ 0.38637916  0.77681173]
 [-0.31101895  1.32393004]
 [ 0.52481897  0.93017452]
 [-1.80514262  0.68941654]
 [-0.4549273   1.23886737]
 [ 0.57630242 -0.26985695]
 [ 0.55313955 -0.54526168]
 [ 0.48710725 -0.40838128]
 [-0.08302013 -0.62906487]
 [ 1.56059284 -0.65791219]
 [ 0.15027096  0.04076371]
 [ 0.31237065  0.12951002]
 [-1.62035383  0.83133128]
 [-0.19490675 -0.6140146 ]
 [-0.26626982 -0.12638371]
 [ 0.05737995 -0.18555394]
 [-0.67606236  0.47094968]
 [ 0.6944272  -0.51327949]
 [ 0.40318583  0.83488332]
 [ 0.08559059  0.12467104]
 [ 0.09971413 -0.67381659]
 [-0.30198176 -0.406786  ]
 [ 1.13817886  0.21892695]
 [-1.50511599 -0.84069479]
 [-0.42883871  0.10042701]
 [-1.08675611  0.27137371]
 [ 1.90888753  2.63690786]
 [ 0.3864213   0.2704046 ]
 [ 0.94307846  0.36825762]
 [ 0.14477626 -0.31530352]
 [-1.60103638 -0.0966127 ]
 

In [ ]:
init = np.random.choice(np.arange(100), size=(4,))
print(init)
centroids = data[np.random.choice(np.arange(100), size=(4,))]
print(centroids)

[43 62 54 71]
[[ 0.13564995 -1.21967852]
 [-0.17370106  0.37889875]
 [ 1.93376669 -0.01865885]
 [-1.50511599 -0.84069479]]


In [ ]:
x = data[0]
# c = [[1, 2],
#      [1, 3],
#      [1, 4],
#      [2, 2]]

distance = np.sum((x - centroids)**2, axis=1)
print(x)
print(type(x))
print(centroids)
print(type(centroids))
print(distance)

[-1.46011327 -1.14851968]
<class 'numpy.ndarray'>
[[ 0.13564995 -1.21967852]
 [-0.17370106  0.37889875]
 [ 1.93376669 -0.01865885]
 [-1.50511599 -0.84069479]]
<class 'numpy.ndarray'>
[ 2.55152383  3.98786342 12.79500663  0.09678141]


In [ ]:
x = np.array([3, 1])
c = np.array([[1, 2], [1, 3], [1, 4], [2, 2]])
distance = np.sum((x - c)**2, axis=1)

print(x)
print(type(x))
print(c)
print(type(c))
print(distance)

[3 1]
<class 'numpy.ndarray'>
[[1 2]
 [1 3]
 [1 4]
 [2 2]]
<class 'numpy.ndarray'>
[ 5  8 13  2]
